In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("IMDB Dataset.csv")

In [3]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df.shape

(50000, 2)

In [5]:
df = df.head(100)

In [6]:
df.shape

(100, 2)

In [7]:
## First lets turn all the text to small. To do that we can use python simple string function

In [8]:
type(df['review'][3])

str

In [9]:
df['review'] = df['review'].str.lower()

In [10]:
df['review']

0     one of the other reviewers has mentioned that ...
1     a wonderful little production. <br /><br />the...
2     i thought this was a wonderful way to spend ti...
3     basically there's a family where a little boy ...
4     petter mattei's "love in the time of money" is...
                            ...                        
95    daniel day-lewis is the most versatile actor a...
96    my guess would be this was originally going to...
97    well, i like to watch bad horror b-movies, cau...
98    this is the worst movie i have ever seen, as w...
99    i have been a mario fan for as long as i can r...
Name: review, Length: 100, dtype: object

In [11]:
df['review'][1]

'a wonderful little production. <br /><br />the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />the actors are extremely well chosen- michael sheen not only "has got all the polari" but he has all the voices down pat too! you can truly see the seamless editing guided by the references to williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. a masterful production about one of the great master\'s of comedy and his life. <br /><br />the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell\'s murals decorating every surface) are terribly well d

In [12]:
## Here we can see multiple html tags. we need to remove those tags. Here we can use butisoup. This python library helps us to extrat data from HTML and XML

In [13]:
from bs4 import BeautifulSoup

In [14]:
BeautifulSoup(df['review'][1], "html.parser").get_text()

'a wonderful little production. the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. the actors are extremely well chosen- michael sheen not only "has got all the polari" but he has all the voices down pat too! you can truly see the seamless editing guided by the references to williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. a masterful production about one of the great master\'s of comedy and his life. the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell\'s murals decorating every surface) are terribly well done.'

In [15]:
##lets applly it to whole column

In [16]:
df['review'] = df['review'].apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())

In [17]:
df['review']

0     one of the other reviewers has mentioned that ...
1     a wonderful little production. the filming tec...
2     i thought this was a wonderful way to spend ti...
3     basically there's a family where a little boy ...
4     petter mattei's "love in the time of money" is...
                            ...                        
95    daniel day-lewis is the most versatile actor a...
96    my guess would be this was originally going to...
97    well, i like to watch bad horror b-movies, cau...
98    this is the worst movie i have ever seen, as w...
99    i have been a mario fan for as long as i can r...
Name: review, Length: 100, dtype: object

In [18]:
## Now lets handle the puntuation 

In [19]:
import string 

In [20]:
exclude = string.punctuation

In [21]:
print(exclude)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [22]:
type(exclude)

str

In [23]:
test_string = df['review'][1]

In [24]:
def remove_punctuation(text):
    for ch in exclude:
        text = text.replace(ch, '')

    return text

In [25]:
test_string = remove_punctuation(test_string)

In [26]:
print(test_string)

a wonderful little production the filming technique is very unassuming very oldtimebbc fashion and gives a comforting and sometimes discomforting sense of realism to the entire piece the actors are extremely well chosen michael sheen not only has got all the polari but he has all the voices down pat too you can truly see the seamless editing guided by the references to williams diary entries not only is it well worth the watching but it is a terrificly written and performed piece a masterful production about one of the great masters of comedy and his life the realism really comes home with the little things the fantasy of the guard which rather than use the traditional dream techniques remains solid then disappears it plays on our knowledge and our senses particularly with the scenes concerning orton and halliwell and the sets particularly of their flat with halliwells murals decorating every surface are terribly well done


In [27]:
## We we can translate method of sting

In [28]:
def remove_punc(text):
    text = text.translate(str.maketrans('','', exclude))
    return text

In [29]:
test_string = remove_punc(test_string)

In [30]:
print(test_string)

a wonderful little production the filming technique is very unassuming very oldtimebbc fashion and gives a comforting and sometimes discomforting sense of realism to the entire piece the actors are extremely well chosen michael sheen not only has got all the polari but he has all the voices down pat too you can truly see the seamless editing guided by the references to williams diary entries not only is it well worth the watching but it is a terrificly written and performed piece a masterful production about one of the great masters of comedy and his life the realism really comes home with the little things the fantasy of the guard which rather than use the traditional dream techniques remains solid then disappears it plays on our knowledge and our senses particularly with the scenes concerning orton and halliwell and the sets particularly of their flat with halliwells murals decorating every surface are terribly well done


In [31]:
df['review'] = df['review'].apply(remove_punc)

In [32]:
df['review']

0     one of the other reviewers has mentioned that ...
1     a wonderful little production the filming tech...
2     i thought this was a wonderful way to spend ti...
3     basically theres a family where a little boy j...
4     petter matteis love in the time of money is a ...
                            ...                        
95    daniel daylewis is the most versatile actor al...
96    my guess would be this was originally going to...
97    well i like to watch bad horror bmovies cause ...
98    this is the worst movie i have ever seen as we...
99    i have been a mario fan for as long as i can r...
Name: review, Length: 100, dtype: object

In [33]:
## Now lets remove the stopwords

In [34]:
from nltk.corpus import stopwords

In [35]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [36]:
def remove_stopwords(text):
    new_text = []
    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    return ' '.join(new_text)

In [37]:
test_string

'a wonderful little production the filming technique is very unassuming very oldtimebbc fashion and gives a comforting and sometimes discomforting sense of realism to the entire piece the actors are extremely well chosen michael sheen not only has got all the polari but he has all the voices down pat too you can truly see the seamless editing guided by the references to williams diary entries not only is it well worth the watching but it is a terrificly written and performed piece a masterful production about one of the great masters of comedy and his life the realism really comes home with the little things the fantasy of the guard which rather than use the traditional dream techniques remains solid then disappears it plays on our knowledge and our senses particularly with the scenes concerning orton and halliwell and the sets particularly of their flat with halliwells murals decorating every surface are terribly well done'

In [38]:
test_string = remove_stopwords(test_string)

In [39]:
print(test_string)

 wonderful little production  filming technique   unassuming  oldtimebbc fashion  gives  comforting  sometimes discomforting sense  realism   entire piece  actors  extremely well chosen michael sheen    got   polari      voices  pat    truly see  seamless editing guided   references  williams diary entries     well worth  watching     terrificly written  performed piece  masterful production  one   great masters  comedy   life  realism really comes home   little things  fantasy   guard  rather  use  traditional dream techniques remains solid  disappears  plays   knowledge   senses particularly   scenes concerning orton  halliwell   sets particularly   flat  halliwells murals decorating every surface  terribly well done


In [40]:
df['review'] = df['review'].apply(remove_stopwords)

In [41]:
df['review']

0     one    reviewers  mentioned   watching  1 oz e...
1      wonderful little production  filming techniqu...
2      thought    wonderful way  spend time    hot s...
3     basically theres  family   little boy jake thi...
4     petter matteis love   time  money   visually s...
                            ...                        
95    daniel daylewis    versatile actor alive engli...
96     guess would    originally going    least two ...
97    well  like  watch bad horror bmovies cause  th...
98       worst movie   ever seen  well   worst    pr...
99        mario fan   long    remember    fond memor...
Name: review, Length: 100, dtype: object

In [42]:
## now lets tokenize and stemp it. for It we can use SpaCy

In [43]:
##let us use transforners because of this we do need to vectorization it will handle that process atuometically
from transformers import AutoTokenizer

C:\Users\SHUBHAM\AppData\Roaming\Python\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [44]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

In [45]:
def tokens(text):
    return tokenizer(text, return_tensors = 'tf', padding=True, truncation=True)

In [46]:
tokens(test_string)

{'input_ids': <tf.Tensor: shape=(1, 102), dtype=int32, numpy=
array([[  101,  6919,  2210,  2537,  7467,  6028, 14477,  4757, 24270,
         2214,  7292, 10322,  2278,  4827,  3957, 16334,  2823, 17964,
         2075,  3168, 15650,  2972,  3538,  5889,  5186,  2092,  4217,
         2745, 20682,  2288, 11508,  2072,  5755,  6986,  5621,  2156,
        25180,  3238,  9260,  8546,  7604,  3766,  9708, 10445,  2092,
         4276,  3666, 27547,  2135,  2517,  2864,  3538,  3040,  3993,
         2537,  2028,  2307,  5972,  4038,  2166, 15650,  2428,  3310,
         2188,  2210,  2477,  5913,  3457,  2738,  2224,  3151,  3959,
         5461,  3464,  5024, 17144,  3248,  3716,  9456,  3391,  5019,
         7175, 25161,  2534,  2072,  4381,  4520,  3391,  4257,  2534,
         2072,  4381,  2015, 19016, 25545,  5844,  2296,  3302, 16668,
         2092,  2589,   102]])>, 'token_type_ids': <tf.Tensor: shape=(1, 102), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [47]:
df['review'] = df['review'].apply(tokens)

In [48]:
df['review'][1]

{'input_ids': <tf.Tensor: shape=(1, 102), dtype=int32, numpy=
array([[  101,  6919,  2210,  2537,  7467,  6028, 14477,  4757, 24270,
         2214,  7292, 10322,  2278,  4827,  3957, 16334,  2823, 17964,
         2075,  3168, 15650,  2972,  3538,  5889,  5186,  2092,  4217,
         2745, 20682,  2288, 11508,  2072,  5755,  6986,  5621,  2156,
        25180,  3238,  9260,  8546,  7604,  3766,  9708, 10445,  2092,
         4276,  3666, 27547,  2135,  2517,  2864,  3538,  3040,  3993,
         2537,  2028,  2307,  5972,  4038,  2166, 15650,  2428,  3310,
         2188,  2210,  2477,  5913,  3457,  2738,  2224,  3151,  3959,
         5461,  3464,  5024, 17144,  3248,  3716,  9456,  3391,  5019,
         7175, 25161,  2534,  2072,  4381,  4520,  3391,  4257,  2534,
         2072,  4381,  2015, 19016, 25545,  5844,  2296,  3302, 16668,
         2092,  2589,   102]])>, 'token_type_ids': <tf.Tensor: shape=(1, 102), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,